#!/bin/bash
set -eu

#
# latest - Retrieve the latest version available,
#          based on a variety of heuristics.
#
# USAGE: latest PACKAGE
#
#  i.e.: latest safe
#        latest cf
#

if [[ -z "${1:-}" ]]; then
  echo >&2 "USAGE: $0 PACKAGE"
  exit 1
fi

from_github() {
  curl -sL https://api.github.com/repos/$1/releases/latest | jq -r .tag_name | sed -e 's/^v//'
}

from_hashicorp() {
  curl -sL https://releases.hashicorp.com/$1/ | grep 'a href="/'$1 | grep -v '[+-]' | head -n1 | sed -e 's/ *<[^>]*>//g;s/^'$1'_//'
}

case $1 in
cf)
  curl -v https://packages.cloudfoundry.org/stable?release=debian64 2>&1 | \
    grep Location | sed -e 's@.*/releases/v@@;s@/.*@@'
  ;;

bbr)         from_github cloudfoundry-incubator/bosh-backup-and-restore ;;
bosh)        from_github cloudfoundry/bosh-cli ;;
credhub)     from_github cloudfoundry-incubator/credhub-cli ;;
fly)         from_github concourse/concourse ;;
genesis)     from_github genesis-community/$1 ;;
kubectl)     from_github kubernetes/kubernetes ;;
safe|gotcha) from_github starkandwayne/$1 ;;
s3|osb|boss) from_github jhunt/$1 ;;
spruce)      from_github geofffranks/$1 ;;
jq)          from_github stedolan/$1 | sed -e 's/^jq-//' ;;
shield)      from_github shieldproject/$1 ;;

vault|terraform) from_hashicorp $1 ;;

*)
  echo >&2 "$0: unrecognized package name '$1'!"
  exit 1
  ;;
esac
