# Regularly rebuild the Docker image, even if nothing
# structurally has changed in the Dockerfile, to get
# the latest virus definitions from upstream.

name: Rebuild the Docker Image

on:
  watch:
    types: [started]
  schedule:
    - cron: '25 * * * *'
      #- cron: '45 23 * * *'

jobs:
  build-and-push:
    name: (Re)Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build && push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo -n $env:DOCKER_PASSWORD | docker login --username $env:DOCKER_USERNAME --password-stdin
          make latest push
